version: '3.3'
services:
  app:
    build:
      context: ./app
    ports:
      - 80:8080
    volumes:
      - type: bind
        source: ./app
        target: /wwwroot
  #   environment:
  #     CHOKIDAR_USEPOLLING: 'true'

  server:
    build:
      context: ./server
    # image: 'wwde_server'
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /wwwroot
    # environment:
      # CHOKIDAR_USEPOLLING: 'true'

# volumes:
#   data-db:
