version: '3.3'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - buildfiles:/usr/share/nginx/html
      - type: volume
        source: buildfiles
        target: /usr/share/nginx/html
        volume:
          nocopy: true
    ports:
      - 80:80
      - 443:443

  app:
    # build:
      # context: ./app
    image: 'lukewilson/wwde-app'
    ports:
      - 8080:8080
    volumes:
      - buildfiles:/wwwroot/dist

  server:
    # build:
      # context: ./server
    image: 'lukewilson/wwde-server'
    ports:
      - 3000:3000

volumes:
  buildfiles: {}
